export * from "./landing-home/landing-home";
export * from "./about-me/about-me";
export * from "./selling-points/selling-points";
export * from "./contact/contact";
export * from "./solutions/solutions";
export * from "./spacer/spacer";
export * from "./header/header";
export * from "./footer/footer";
export * from "./article/article";
