/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { lazy, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gameboy.glb', lazy=true)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gameboy_Green.geometry} material={materials.Red} />
    </group>
  )
}

useGLTF.preload('/gameboy.glb')
